{"name": "Verify albanian and hungarian are here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.001\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Lingocard_text_on_main_page.py\", line 5, in open_homepage\n    context.app.main_page.open_page()\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\Lingocard_text_on_main_page\\pages\\base_page.py\", line 31, in open_page\n    self.driver.get(self.base_url + url)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.001\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Lingocard_text_on_main_page.py\", line 5, in open_homepage\n    context.app.main_page.open_page()\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\Lingocard_text_on_main_page\\pages\\base_page.py\", line 31, in open_page\n    self.driver.get(self.base_url + url)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1589333048188, "stop": 1589333348194}, {"name": "Then Verify Albanian is here", "status": "skipped", "start": 1589333350291, "stop": 1589333350291}, {"name": "Then Verify Hungarian is here", "status": "skipped", "start": 1589333350291, "stop": 1589333350291}], "start": 1589333039061, "stop": 1589333350291, "uuid": "1e30c3cd-2a67-445e-9baa-d79bf3a0bebe", "historyId": "a82ead3a1d00b5cc995328c663c1b5bb", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Lingocard_albanian_hungarian_are_here"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}